name: Check Branch Name
on: pull_request

jobs:
  check_branch_name:
    name: check_branch_name
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name is valid
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^PMISK-\d\\{1,6\\}$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            exit 1
          else
            echo "✅ Valid branch name: $BRANCH_NAME"
          fi