name: Check Branch Name
on: pull_request

jobs:
  check_branch_name:
    name: check_branch_name
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name is valid
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Checking branch: $BRANCH_NAME"
          if [[ ! "PMISK-9" =~ ^PMISK-\d{1,6}$ ]]; then
            echo "❌ Invalid branch name"
            exit 1
          else
            echo "✅ Valid branch name"
          fi